# Generated by Django 3.2.13 on 2023-03-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=500)),
                ('receiver', models.CharField(max_length=500)),
                ('message', models.TextField()),
            ],
        ),
    ]
